### ISSUE TITLE
Modularize:  Hacktober Fest 23 label

### ISSUE THREAD

**Issue by Soyvor** [KOMNOOB/The-Hideout#5]
Modularize: 

Separate different parts of the code into functions for better code structure and reusability.

**Comment by k0msenapati** [comment]
Use Classes:

Organize the code into classes to improve readability and maintainability.

**Comment by Dhanush0369** [comment]
Hi, I want work on this. Can you assign it to me.

**Comment by k0msenapati** [comment]
Ok @Dhanush0369 start working on this issue.

**Comment by k0msenapati** [comment]
Any update @Dhanush0369 ?

**Comment by Vinay-Singh-Chauhan** [comment]
I want to give it a try.  Can you assign it to me? @kom-senapati

**Comment by k0msenapati** [comment]
Ok go ahead

**Comment by kom-senapati** [comment]
Awesome work @Vinay-Singh-Chauhan

**Comment by k0msenapati** [comment]
Awesome work @Vinay-Singh-Chauhan
